# Generated by Django 3.1.7 on 2021-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_pizza', models.CharField(max_length=50)),
                ('number_of_pizza', models.IntegerField()),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='Large', max_length=1)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_number', models.IntegerField()),
                ('customer_address', models.CharField(max_length=100)),
                ('status_of_order', models.CharField(choices=[('ORDER RECEVIED', 'Order Received'), ('ORDER PLACED', 'Order Placed'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered')], max_length=30)),
            ],
        ),
    ]
